export let API = {
	url: 'http://162.14.111.196:4000',
	loginByCellphone: '/login/cellphone',
	getLoginCaptcha: '/captcha/sent',
	verifyLoginCaptcha: '/captcha/verify',
	banner: '/banner',
	homePageJson: '/homepage/block/page',
	getUrlBySongId: '/song/url',
	getSongDetail: '/song/detail',
	search: '/cloudsearch',
	getArtistDetail: '/artist/detail',
	getArtistFans: '/artist/fans',
	hotSearch: '/search/hot/detail',
	getTopList: '/toplist',
	getListDetail: '/playlist/detail',
	getListSongs: '/playlist/track/all',
	recommendedSonglist: '/personalized',
};
